{
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
        "ID": "CVE-2021-4178",
        "ASSIGNER": "secalert@redhat.com",
        "STATE": "PUBLIC"
    },
    "affects": {
        "vendor": {
            "vendor_data": [
                {
                    "vendor_name": "n/a",
                    "product": {
                        "product_data": [
                            {
                                "product_name": "kubernetes-client",
                                "version": {
                                    "version_data": [
                                        {
                                            "version_value": "Affects 5.x versions, Fixed in kubernetes-client v5.0.3 and above."
                                        }
                                    ]
                                }
                            }
                        ]
                    }
                }
            ]
        }
    },
    "problemtype": {
        "problemtype_data": [
            {
                "description": [
                    {
                        "lang": "eng",
                        "value": "CWE-502 - Deserialization of Untrusted Data"
                    }
                ]
            }
        ]
    },
    "references": {
        "reference_data": [
            {
                "refsource": "MISC",
                "name": "https://bugzilla.redhat.com/show_bug.cgi?id=2034388",
                "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2034388"
            },
            {
                "refsource": "MISC",
                "name": "https://access.redhat.com/security/cve/CVE-2021-4178",
                "url": "https://access.redhat.com/security/cve/CVE-2021-4178"
            },
            {
                "refsource": "MISC",
                "name": "https://github.com/advisories/GHSA-98g7-rxmf-rrxm",
                "url": "https://github.com/advisories/GHSA-98g7-rxmf-rrxm"
            },
            {
                "refsource": "MISC",
                "name": "https://github.com/fabric8io/kubernetes-client/issues/3653",
                "url": "https://github.com/fabric8io/kubernetes-client/issues/3653"
            }
        ]
    },
    "description": {
        "description_data": [
            {
                "lang": "eng",
                "value": "A arbitrary code execution flaw was found in the Fabric 8 Kubernetes client affecting versions 5.0.0-beta-1 and above. Due to an improperly configured YAML parsing, this will allow a local and privileged attacker to supply malicious YAML."
            }
        ]
    }
}