{
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
        "ID": "CVE-2021-30499",
        "ASSIGNER": "secalert@redhat.com",
        "STATE": "PUBLIC"
    },
    "affects": {
        "vendor": {
            "vendor_data": [
                {
                    "vendor_name": "n/a",
                    "product": {
                        "product_data": [
                            {
                                "product_name": "libcaca",
                                "version": {
                                    "version_data": [
                                        {
                                            "version_value": "master"
                                        }
                                    ]
                                }
                            }
                        ]
                    }
                }
            ]
        }
    },
    "problemtype": {
        "problemtype_data": [
            {
                "description": [
                    {
                        "lang": "eng",
                        "value": "CWE-119"
                    }
                ]
            }
        ]
    },
    "references": {
        "reference_data": [
            {
                "refsource": "MISC",
                "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1948679",
                "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1948679"
            },
            {
                "refsource": "MISC",
                "name": "https://github.com/cacalabs/libcaca/issues/54",
                "url": "https://github.com/cacalabs/libcaca/issues/54"
            }
        ]
    },
    "description": {
        "description_data": [
            {
                "lang": "eng",
                "value": "A flaw was found in libcaca. A buffer overflow of export.c in function export_troff might lead to memory corruption and other potential consequences."
            }
        ]
    }
}